<h2>System Checks</h2>

<?php
if ($this->DB['result']) {
	$panelClass = 'panel-success';
} else {
	$panelClass = 'panel-danger';
}
?>
<div class="panel <?php echo $panelClass; ?>">
  <div class="panel-heading">
    <h3 class="panel-title">Database Connection &amp; Availability</h3>
  </div>
  <div class="panel-body">
    <p><?php echo $this->DB['message'];  ?></p>
  </div>
</div>

<?php
if ($this->TBL_AGENCIES['result'] && $this->TBL_ZIPS['result']) {
	$panelClass = 'panel-success';
} else {
	$panelClass = 'panel-danger';
}
?>
<div class="panel <?php echo $panelClass; ?>">
  <div class="panel-heading">
    <h3 class="panel-title">Required Database Tables</h3>
  </div>
  <div class="panel-body">
    <p><strong>Agencies:</strong> <?php echo $this->TBL_AGENCIES['message'];  ?></p>
	<p><strong>Zip Codes:</strong> <?php echo $this->TBL_ZIPS['message'];  ?></p>
  </div>
</div>

<?php
if ($this->TBL_AGENCIES_COUNT['result'] && $this->TBL_ZIPS_COUNT['result']) {
	$panelClass = 'panel-success';
} else {
	$panelClass = 'panel-danger';
}
?>
<div class="panel <?php echo $panelClass; ?>">
  <div class="panel-heading">
    <h3 class="panel-title">Required Data</h3>
  </div>
  <div class="panel-body">
    <p><strong>Agencies:</strong> <?php echo $this->TBL_AGENCIES_COUNT['message'];  ?></p>
	<p><strong>Zip Codes:</strong> <?php echo $this->TBL_ZIPS_COUNT['message'];  ?></p>
  </div>
</div>