<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">1. Follow Development</h3>
            </div>
            <div class="panel-body">
                <p>If you are interested in following the development of HUD_HCA, or need to submit an issue please visit the repo on Github! You can also clone the code to host and/or improve yourself.</p>
                <p><a class="btn btn-success pull-right" href="https://github.com/bentigano/HUD_HCA" target="_blank">Development &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">2. Learn</h3>
            </div>
            <div class="panel-body">
                <p>See why this application was created, and what problems it solves.</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('HCA') ?>" target="_blank">Learn More &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">3. Submit Requests</h3>
            </div>
            <div class="panel-body">
                <p>Start learning about and using the API to get back HUD-approved housing counseling agencies!</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('HCA', array('action' => 'usage')) ?>" target="_blank">Use the API &raquo;</a></p>
            </div>
        </div>
    </div>
	
</div>
